### Step 1 — Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

### Step 2 — Load the Clean Dataset

In [2]:
df = pd.read_csv("../Dataset/f1_clean_data.csv")

print("Dataset loaded successfully!")
print("Dataset Shape:", df.shape)

df.head()

Dataset loaded successfully!
Dataset Shape: (7129, 30)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,year,podium,driver_name,constructor_name,round,race_name,circuitId,date,circuit_name,location,country,qualifying_position
0,20323,337,4,6,8,3,1,1,1,25.0,49,1:39:20.396,5960396,45,1,1:58.287,191.706,1,2010,1,Fernando Alonso,Ferrari,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,3.0
1,20324,337,13,6,7,2,2,2,2,18.0,49,+16.099,5976495,38,5,1:59.732,189.392,1,2010,1,Felipe Massa,Ferrari,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,2.0
2,20325,337,1,1,2,4,3,3,3,15.0,49,+23.182,5983578,42,4,1:59.560,189.665,1,2010,1,Lewis Hamilton,McLaren,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,4.0
3,20326,337,20,9,5,1,4,4,4,12.0,49,+38.799,5999195,32,12,2:00.218,188.627,1,2010,0,Sebastian Vettel,Red Bull,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,1.0
4,20327,337,3,131,4,5,5,5,5,10.0,49,+40.213,6000609,45,13,2:00.236,188.599,1,2010,0,Nico Rosberg,Mercedes,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,5.0

### Step 3 — Check Dataset Shape and Columns

In [3]:
print("Dataset Shape:", df.shape)

print("\nTotal Columns:", len(df.columns))

print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (7129, 30)

Total Columns: 30

Columns:
['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid', 'position', 'positionText', 'positionOrder', 'points', 'laps', 'time', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime', 'fastestLapSpeed', 'statusId', 'year', 'podium', 'driver_name', 'constructor_name', 'round', 'race_name', 'circuitId', 'date', 'circuit_name', 'location', 'country', 'qualifying_position']

#### Step 4 — Check Data Types

In [4]:
df.dtypes

resultId                 int64
raceId                   int64
driverId                 int64
constructorId            int64
number                   int64
grid                       str
position                   str
positionText               str
positionOrder            int64
points                 float64
laps                     int64
time                       str
milliseconds               str
fastestLap                 str
rank                       str
fastestLapTime             str
fastestLapSpeed            str
statusId                 int64
year                     int64
podium                   int64
driver_name                str
constructor_name           str
round                    int64
race_name                  str
circuitId                int64
date                       str
circuit_name               str
location                   str
country                    str
qualifying_position    float64
dtype: object

### Step 5 — Check Missing Values

In [5]:
df.isnull().sum()

resultId               0
raceId                 0
driverId               0
constructorId          0
number                 0
grid                   0
position               0
positionText           0
positionOrder          0
points                 0
laps                   0
time                   0
milliseconds           0
fastestLap             0
rank                   0
fastestLapTime         0
fastestLapSpeed        0
statusId               0
year                   0
podium                 0
driver_name            0
constructor_name       0
round                  0
race_name              0
circuitId              0
date                   0
circuit_name           0
location               0
country                0
qualifying_position    0
dtype: int64

### Step 6 — Check Duplicate Records

In [6]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

### Step 7 — Check \N Missing Values

In [7]:
missing_n = (df.astype(str) == r"\N").sum()

missing_n[missing_n > 0]

grid                 20
position           1032
time               3375
milliseconds       3375
fastestLap          313
rank                 58
fastestLapTime      313
fastestLapSpeed     999
dtype: int64

### Step 8 — Replace \N with NaN

In [8]:
df = df.replace(r"\N", np.nan)

print("All \\N values replaced with NaN successfully!")

All \N values replaced with NaN successfully!

### Step 9 — Check Missing Values After Replacement

In [9]:
df.isnull().sum()

resultId                  0
raceId                    0
driverId                  0
constructorId             0
number                    0
grid                     20
position               1032
positionText              0
positionOrder             0
points                    0
laps                      0
time                   3375
milliseconds           3375
fastestLap              313
rank                     58
fastestLapTime          313
fastestLapSpeed         999
statusId                  0
year                      0
podium                    0
driver_name               0
constructor_name          0
round                     0
race_name                 0
circuitId                 0
date                      0
circuit_name              0
location                  0
country                   0
qualifying_position       0
dtype: int64

### Step 10 — Convert Important Numeric Columns

In [10]:
numeric_columns = [
    "grid",
    "position",
    "time",
    "milliseconds",
    "fastestLap",
    "rank",
    "fastestLapSpeed",
    "qualifying_position"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

print("Numeric columns converted successfully!")

Numeric columns converted successfully!

### Step 11 — Check Data Types After Conversion

In [11]:
df[
    [
        "grid",
        "position",
        "time",
        "milliseconds",
        "fastestLap",
        "rank",
        "fastestLapSpeed",
        "qualifying_position"
    ]
].dtypes

grid                   float64
position               float64
time                   float64
milliseconds           float64
fastestLap             float64
rank                   float64
fastestLapSpeed        float64
qualifying_position    float64
dtype: object

### Step 12 — Remove Rows with Missing Grid Position

In [12]:
df = df.dropna(
    subset=["grid"]
).copy()

print("Dataset Shape:", df.shape)
print("Missing Grid Values:", df["grid"].isnull().sum())

Dataset Shape: (7109, 30)
Missing Grid Values: 0

### Step 13 — Check Missing Values Percentage

In [13]:
missing_percentage = (
    df.isnull().sum() / len(df) * 100
).sort_values(ascending=False)

missing_percentage[missing_percentage > 0]

time               52.145168
milliseconds       47.376565
position           14.516810
fastestLapSpeed    13.771276
fastestLapTime      4.402870
fastestLap          4.402870
rank                0.815867
dtype: float64

### Step 14 — Remove Unnecessary High-Missing Columns

In [14]:
columns_to_drop = [
    "time",
    "milliseconds"
]

df = df.drop(
    columns=columns_to_drop
)

print("Columns removed successfully!")
print("Dataset Shape:", df.shape)

Columns removed successfully!
Dataset Shape: (7109, 28)

### Step 15 — Check Remaining Missing Values

In [15]:
df.isnull().sum()[df.isnull().sum() > 0]

position           1032
fastestLap          313
rank                 58
fastestLapTime      313
fastestLapSpeed     979
dtype: int64

### Step 16 — Handle Remaining Missing Values

In [17]:
df["position"] = df["position"].fillna(df["positionOrder"])
df["fastestLap"] = df["fastestLap"].fillna(df["fastestLap"].median())
df["rank"] = df["rank"].fillna(df["rank"].median())
df["fastestLapSpeed"] = df["fastestLapSpeed"].fillna(
    df["fastestLapSpeed"].median()
)

print("Remaining missing values handled successfully!")

Remaining missing values handled successfully!

### Step 17 — Verify Missing Values After Cleaning

In [19]:
df.isnull().sum()[df.isnull().sum() > 0]

fastestLapTime    313
dtype: int64

### Step 18 — Check Duplicates After Cleaning

In [20]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

### Step 19 — Save Final Cleaned Dataset

In [22]:
df.to_csv(
    "../Dataset/f1_final_cleaned_data.csv",
    index=False
)

print("Final cleaned dataset saved successfully!")
print("Final Dataset Shape:", df.shape)

Final cleaned dataset saved successfully!
Final Dataset Shape: (7109, 28)

### Step 20 — Verify Saved Final Cleaned Dataset

In [23]:
final_df = pd.read_csv(
    "../Dataset/f1_final_cleaned_data.csv"
)

print("Dataset Shape:", final_df.shape)
print("Duplicate Rows:", final_df.duplicated().sum())
print("Total Missing Values:", final_df.isnull().sum().sum())

final_df.head()

Dataset Shape: (7109, 28)
Duplicate Rows: 0
Total Missing Values: 313

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,year,podium,driver_name,constructor_name,round,race_name,circuitId,date,circuit_name,location,country,qualifying_position
0,20323,337,4,6,8,3.0,1.0,1,1,25.0,49,45.0,1.0,1:58.287,191.706,1,2010,1,Fernando Alonso,Ferrari,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,3.0
1,20324,337,13,6,7,2.0,2.0,2,2,18.0,49,38.0,5.0,1:59.732,189.392,1,2010,1,Felipe Massa,Ferrari,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,2.0
2,20325,337,1,1,2,4.0,3.0,3,3,15.0,49,42.0,4.0,1:59.560,189.665,1,2010,1,Lewis Hamilton,McLaren,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,4.0
3,20326,337,20,9,5,1.0,4.0,4,4,12.0,49,32.0,12.0,2:00.218,188.627,1,2010,0,Sebastian Vettel,Red Bull,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,1.0
4,20327,337,3,131,4,5.0,5.0,5,5,10.0,49,45.0,13.0,2:00.236,188.599,1,2010,0,Nico Rosberg,Mercedes,1,Bahrain Grand Prix,3,2010-03-14,Bahrain International Circuit,Sakhir,Bahrain,5.0