### Step 1 — Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

import joblib

pd.set_option("display.max_columns", None)

### Step 2 — Load Feature Engineered Dataset

In [5]:
import pandas as pd

df = pd.read_csv(
    "../Dataset/f1_feature_engineered_data.csv"
)

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (7109, 17)

,year,round,driverId,constructorId,circuitId,grid,qualifying_position,driver_experience,constructor_experience,grid_advantage,qualifying_advantage,driver_avg_points,driver_podium_rate,constructor_podium_rate,recent_driver_points,recent_constructor_points,target_podium
0,2010,1,1,1,3,4.0,4.0,0,0,1.0,1.0,14.350592,0.532544,0.186667,15.000000,15.000000,1
1,2010,2,1,1,1,11.0,11.0,0,0,5.0,5.0,14.350592,0.532544,0.186667,11.500000,11.500000,0
2,2010,3,1,1,2,20.0,20.0,0,0,14.0,14.0,14.350592,0.532544,0.186667,10.333333,10.333333,0
3,2010,4,1,1,17,6.0,6.0,0,0,4.0,4.0,14.350592,0.532544,0.186667,12.250000,12.250000,1
4,2010,5,1,1,4,3.0,3.0,0,0,-11.0,-11.0,14.350592,0.532544,0.186667,9.800000,9.800000,0

### Step 3 — Separate Features and Target

In [6]:
X = df.drop(
    "target_podium",
    axis=1
)

y = df["target_podium"]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Shape: (7109, 16)
Target Shape: (7109,)

### Step 4 — Check Target Distribution

In [8]:
y.value_counts()

target_podium
0    6092
1    1017
Name: count, dtype: int64

### Step 5 — Split Training and Testing Data

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (5687, 16)
Testing Shape: (1422, 16)

### Logistic Regression
Step 6 — Train Logistic Regression Model

In [10]:
logistic_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

logistic_model.fit(
    X_train,
    y_train
)

print("Logistic Regression trained successfully!")

Logistic Regression trained successfully!

### Step 7 — Logistic Regression Predictions

In [11]:
lr_pred = logistic_model.predict(
    X_test
)

lr_prob = logistic_model.predict_proba(
    X_test
)[:,1]

print("Predictions generated!")

Predictions generated!

### Step 8 — Evaluate Logistic Regression

In [12]:
lr_accuracy = accuracy_score(
    y_test,
    lr_pred
)

lr_auc = roc_auc_score(
    y_test,
    lr_prob
)

print("Accuracy:", lr_accuracy)
print("ROC-AUC:", lr_auc)

Accuracy: 1.0
ROC-AUC: 1.0

### Step 9 — Logistic Regression Classification Report

In [13]:
print(
    classification_report(
        y_test,
        lr_pred
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1219
           1       1.00      1.00      1.00       203

    accuracy                           1.00      1422
   macro avg       1.00      1.00      1.00      1422
weighted avg       1.00      1.00      1.00      1422

### Step 10 — Logistic Regression Confusion Matrix

In [14]:
lr_cm = confusion_matrix(
    y_test,
    lr_pred
)

print(lr_cm)

[[1219    0]
 [   0  203]]

### Random Forest
Step 11 — Train Random Forest Model

In [15]:
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train,
    y_train
)

print("Random Forest trained successfully!")

Random Forest trained successfully!

### Step 12 — Random Forest Predictions

In [16]:
rf_pred = rf_model.predict(
    X_test
)

rf_prob = rf_model.predict_proba(
    X_test
)[:,1]

print("Predictions generated!")

Predictions generated!

### Step 13 — Evaluate Random Forest

In [17]:
rf_accuracy = accuracy_score(
    y_test,
    rf_pred
)

rf_auc = roc_auc_score(
    y_test,
    rf_prob
)

print("Accuracy:", rf_accuracy)
print("ROC-AUC:", rf_auc)

Accuracy: 0.9760900140646976
ROC-AUC: 0.9966054708494809

#### Step 14 — Random Forest Classification Report

In [18]:
print(
    classification_report(
        y_test,
        rf_pred
    )
)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1219
           1       0.92      0.92      0.92       203

    accuracy                           0.98      1422
   macro avg       0.95      0.95      0.95      1422
weighted avg       0.98      0.98      0.98      1422

### Step 15 — Random Forest Confusion Matrix

In [19]:
rf_cm = confusion_matrix(
    y_test,
    rf_pred
)

print(rf_cm)

[[1202   17]
 [  17  186]]

### XGBoost
Step 16 — Train XGBoost Model

In [20]:
xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    random_state=42
)

xgb_model.fit(
    X_train,
    y_train
)

print("XGBoost trained successfully!")

XGBoost trained successfully!

### Step 17 — XGBoost Predictions

In [21]:
xgb_pred = xgb_model.predict(
    X_test
)

xgb_prob = xgb_model.predict_proba(
    X_test
)[:,1]

print("Predictions generated!")

Predictions generated!

### Step 18 — Evaluate XGBoost

In [22]:
xgb_accuracy = accuracy_score(
    y_test,
    xgb_pred
)

xgb_auc = roc_auc_score(
    y_test,
    xgb_prob
)

print("Accuracy:", xgb_accuracy)
print("ROC-AUC:", xgb_auc)

Accuracy: 0.9915611814345991
ROC-AUC: 0.999765615844369

### Step 19 — XGBoost Classification Report

In [23]:
print(
    classification_report(
        y_test,
        xgb_pred
    )
)

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1219
           1       0.99      0.95      0.97       203

    accuracy                           0.99      1422
   macro avg       0.99      0.97      0.98      1422
weighted avg       0.99      0.99      0.99      1422

### Step 20 — XGBoost Confusion Matrix

In [24]:
xgb_cm = confusion_matrix(
    y_test,
    xgb_pred
)

print(xgb_cm)

[[1218    1]
 [  11  192]]

### Model Comparison
Step 21 — Compare All Models

In [25]:
model_comparison = pd.DataFrame({

    "Model":[
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy":[
        lr_accuracy,
        rf_accuracy,
        xgb_accuracy
    ],

    "ROC_AUC":[
        lr_auc,
        rf_auc,
        xgb_auc
    ]

})


model_comparison.sort_values(
    "ROC_AUC",
    ascending=False
)

                 Model  Accuracy   ROC_AUC
0  Logistic Regression  1.000000  1.000000
2              XGBoost  0.991561  0.999766
1        Random Forest  0.976090  0.996605

### Step 22 — Select Best Model

In [26]:
best_model = model_comparison.loc[
    model_comparison["ROC_AUC"].idxmax(),
    "Model"
]

print("Best Model:", best_model)

Best Model: Logistic Regression

### Step 23 — Save Best Model (XGBoost)

In [28]:
joblib.dump(
    xgb_model,
    "../models/xgboost_podium_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!

### Step 24 — Save Test Data

In [29]:
X_test.to_csv(
    "../Dataset/X_test.csv",
    index=False
)

y_test.to_csv(
    "../Dataset/y_test.csv",
    index=False
)

print("Test data saved successfully!")

Test data saved successfully!

### Step 25 — Final Training Summary

In [30]:
print("Model Training Completed Successfully!")

print("\nBest Model: XGBoost")
print("Accuracy:", round(xgb_accuracy*100,2), "%")
print("ROC-AUC:", round(xgb_auc,4))

print("\nTraining Records:", len(X_train))
print("Testing Records:", len(X_test))

Model Training Completed Successfully!

Best Model: XGBoost
Accuracy: 99.16 %
ROC-AUC: 0.9998

Training Records: 5687
Testing Records: 1422